### PR TITLE
Random select

### PR DESCRIPTION
**Pull request by LizBailey75**

### CODE REVIEW

**Review by ChallisShell — CHANGES_REQUESTED** [review]
46  let ingridients = 'strIngredient' + i;
47   if ((drinks[0][measures]) && (drinks[0][ingridients]) !== "") {
48        result = result + ` <p>${drinks[0][measures]} ${drinks[0][ingridients]}</p>`;

lines 46,, 47, & 48 ingredients is spelled incorrectly

**Review by ChallisShell — CHANGES_REQUESTED** [review]
per script.js lines 54-56 ingredients is spelled incorrectly 

54   let ingridients = 'strIngredient' + i;
55        if ((drinks[0][measures]) && (drinks[0][ingridients]) !== "") {
56            result = result + ` <p>${drinks[0][measures]} ${drinks[0][ingridients]}</p>`

                                                                              
**************************************************************
per script.js lines 56-58  ingredients is spelled incorrectly 

56  var ingridients = 'strIngredient' + i;
57    if ((cocktailData.drinks[0].measures) && (cocktailData.drinks[0].ingridients) !== "") {
58     result = result + ` <p>${cocktailData.drinks[0].measures} ${cocktailData.drinks[0].ingridients}</p>`;

*************************************************************
per script.js  lines 99 to 101 ingredients is spelled incorrectly

99    let ingridients = 'strIngredient' + i;
100    if ((drinks[0][measures]) && (drinks[0][ingridients]) !== "") {
101        result = result + ` <p>${drinks[0][measures]} ${drinks[0][ingridients]}</p>`

**Comment by LizBailey75** [comment]
spelling corrected

**Review by ChallisShell — DISMISSED** [review]
per script.js lines 57 & 58   'ingredients' is spelled incorrectly 

if ((cocktailData.drinks[0].measures) && (cocktailData.drinks[0].ingridients) !== "") {
            result = result + ` <p>${cocktailData.drinks[0].measures} ${cocktailData.drinks[0].ingridients}</p>`;

**Review by ChallisShell — APPROVED** [review]

**Review by ChallisShell — APPROVED** [review]

**Review by ChallisShell — CHANGES_REQUESTED** [review]
per eb-nonworking-script-js file
lines 46, 47, 48, 52, 53, 54, 91,92 & 93 ingredients is spelled incorrectly

**Review by ChallisShell — DISMISSED** [review]
per script.js file
lines 99, 100 & 101 ingredients is spelled incorrectly

**Comment by LizBailey75** [comment]
updated and replaced that section

**Review by ChallisShell — APPROVED** [review]

**Comment by ChallisShell** [comment]
Cool

**Pull request merged**
